kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: repd-west2-b-c
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
  zones: europe-west2-b, europe-west2-c
